package com.cube.nanotimer.smartcube.step;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import com.cube.nanotimer.smartcube.cube.CubieCube;
import com.cube.nanotimer.smartcube.model.CubeRotation;
import com.cube.nanotimer.smartcube.model.CubeMove;
import com.cube.nanotimer.smartcube.model.CubeState;
import com.cube.nanotimer.smartcube.model.Face;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import org.junit.Test;

/**
 * Solves shot rather than cycled: Old Pochmann, where one algorithm trades the buffer's piece for
 * its target and hands two pieces of the other type back and forth doing it, and M2.
 *
 * <p>The solves are generated by {@link SyntheticTwoCycleSolve} from random scrambles, so the memo
 * is known before the detector sees anything and every algorithm can be checked by name. The
 * detector is told the buffers and that the solver swaps, as the app tells it from the solve type's
 * blind method. The three-cycle solves that must read as before are in
 * {@link RecordedBlindSolveTest}.
 */
public class BlindTwoCycleTest {

  private static final String[] FACES = {"U", "R", "F", "D", "L", "B"};
  private static final String[] SUFFIXES = {"", "'", "2"};

  /** Enough scrambles to meet cycle breaks, flipped pieces and twisted ones many times over. */
  private static final int SCRAMBLES = 300;

  @Test
  public void readsEveryAlgorithmOfAnOldPochmannSolve() {
    Random random = new Random(20260819);
    for (int attempt = 0; attempt < SCRAMBLES; attempt++) {
      String scramble = scramble(random);
      SyntheticTwoCycleSolve solve = oldPochmann(scramble);
      BlindStepDetector detector = read(scramble, solve, "UR", "ULB");

      assertEquals(scramble, names(solve), read(detector));
      assertTrue(scramble, detector.matchesMethod());
      assertTrue(scramble, detector.isComplete());
    }
  }

  /** M2 is an edge method, so it is solved beside Old Pochmann corners, run first. */
  @Test
  public void readsEveryAlgorithmOfAnM2Solve() {
    Random random = new Random(20260819);
    for (int attempt = 0; attempt < SCRAMBLES; attempt++) {
      String scramble = scramble(random);
      SyntheticTwoCycleSolve solve = m2(scramble);
      BlindStepDetector detector = read(scramble, solve, "DF", "ULB");

      assertEquals(scramble, names(solve), read(detector));
      assertTrue(scramble, detector.matchesMethod());
      assertTrue(scramble, detector.isComplete());
    }
  }

  @Test
  public void splitsAnOldPochmannSolveIntoMemoEdgesAndCorners() {
    String scramble = scramble(new Random(11));
    SyntheticTwoCycleSolve solve = oldPochmann(scramble);
    BlindStepDetector detector = read(scramble, solve, "UR", "ULB");

    assertEquals(3, detector.stepCount());
    assertEquals("memo", detector.stepName(0));
    assertEquals("edges", detector.stepName(1));
    assertEquals("corners", detector.stepName(2));
    assertEquals(solve.shots().size(), detector.subStepCount(1) + detector.subStepCount(2));
  }

  /** Declared, a swap is read from the first one: nothing waits for a run of them. */
  @Test
  public void readsTheFirstTwoShotsAsSwaps() {
    String scramble = scramble(new Random(7));
    List<SyntheticTwoCycleSolve.Shot> shots = oldPochmann(scramble).shots().subList(0, 2);
    BlindStepDetector detector = new BlindStepDetector();
    detector.setBuffers("UR", "ULB");
    detector.setSwaps(true);
    play(scrambled(scramble), detector, moves(shots));

    assertEquals(Arrays.asList(shots.get(0).name, shots.get(1).name), read(detector));
  }

  /** Not declared, the same swaps are no algorithm a 3-styler runs, and read as none. */
  @Test
  public void readsNoSwapWhereTheSolverCycles() {
    String scramble = scramble(new Random(7));
    List<SyntheticTwoCycleSolve.Shot> shots = oldPochmann(scramble).shots().subList(0, 2);
    BlindStepDetector detector = new BlindStepDetector();
    detector.setBuffers("UR", "ULB");
    play(scrambled(scramble), detector, moves(shots));

    List<String> read = read(detector);
    assertTrue(read.toString(), read.size() >= shots.size()); // or the loop checks nothing
    for (String name : read) {
      assertFalse(name, name.matches("UR-[A-Z]+"));
    }
  }

  /** Three-cycles read as three-cycles whichever way the solver shoots, so a hybrid is read whole. */
  @Test
  public void readsAThreeCycleSolveAsThreeCyclesEitherWay() {
    String uPerm = "R2 U R U R' U' R' U' R' U R'";
    String aPerm = "R' F R' B2 R F' R' B2 R2";
    List<String> solution = new ArrayList<String>();
    for (String setup : new String[] {"", "F2", "L2"}) {
      solution.add(conjugate(setup, uPerm));
    }
    for (String setup : new String[] {"", "U2"}) {
      solution.add(conjugate(setup, aPerm));
    }
    String moves = String.join(" ", solution);
    for (boolean swaps : new boolean[] {false, true}) {
      CubieCube cube = new CubieCube();
      for (String token : invert(moves).split(" ")) {
        applyToken(cube, token);
      }
      BlindStepDetector detector = new BlindStepDetector();
      detector.setSwaps(swaps);
      play(cube, detector, moves.split(" "));

      List<String> read = read(detector);
      assertEquals(read.toString(), solution.size(), read.size());
      for (String name : read) {
        assertEquals(name, 3, name.split("-").length);
      }
    }
  }

  /**
   * Four edges in two exchanges, one holding the buffer: M2's shape, each a slice that drifts the
   * frame. Not a method's target order, only that such a swap is read and shot from its buffer.
   */
  @Test
  public void readsAlgorithmsThatSwapTwoPairsOfTheSameType() {
    String scramble = scramble(new Random(3));
    String[] setups = {"U", "R", "U2", "B"};
    SyntheticTwoCycleSolve solve = new SyntheticTwoCycleSolve();
    solve.scramble(scramble);
    for (String setup : setups) {
      solve.shoot("M2", setup);
    }
    BlindStepDetector detector = read(scramble, solve, "DF", "ULB");

    List<String> read = read(detector);
    assertEquals(read.toString(), setups.length, read.size());
    for (String name : read) {
      assertTrue(name, name.startsWith("DF-"));
    }
  }

  /** Stopped short, every algorithm read was right: nothing red, and no parity said to be skipped. */
  @Test
  public void blamesNothingOnASolveStoppedShort() {
    Random random = new Random(20260925);
    for (int attempt = 0; attempt < SCRAMBLES / 3; attempt++) {
      String scramble = scramble(random);
      for (boolean op : new boolean[] {true, false}) {
        List<List<String>> made = made(op ? oldPochmann(scramble) : m2(scramble));
        for (int kept : new int[] {made.size() - 1, made.size() / 2}) {
          BlindStepDetector detector = replay(scramble, made.subList(0, kept), op);

          assertEquals(scramble, -1, firstRed(detector));
          assertEquals(scramble, null, detector.getParityCheck());
        }
      }
    }
  }

  /** A memo item skipped: the algorithms before it stay clean, whichever way the solver shoots. */
  @Test
  public void blamesNothingBeforeASkippedMemoItem() {
    Random random = new Random(20260925);
    for (int attempt = 0; attempt < SCRAMBLES / 3; attempt++) {
      String scramble = scramble(random);
      for (boolean op : new boolean[] {true, false}) {
        List<List<String>> made = made(op ? oldPochmann(scramble) : m2(scramble));
        int skipped = 1 + random.nextInt(made.size() - 2);
        made.remove(skipped);
        BlindStepDetector detector = replay(scramble, made, op);

        int red = firstRed(detector);
        assertTrue(scramble + " red at " + red, red < 0 || red >= skipped);
      }
    }
  }

  /** The shot that took a skipped item's turn is red, and says the one target the cube owed. */
  @Test
  public void namesTheSkippedTargetOnTheSwapThatMissedIt() {
    String scramble = scramble(new Random(11));
    SyntheticTwoCycleSolve solve = oldPochmann(scramble);
    List<List<String>> made = made(solve);
    made.remove(6);
    BlindStepDetector detector = replay(scramble, made, true);

    assertEquals(6, firstRed(detector));
    assertEquals(solve.shots().get(6).name, detector.subStepWantedName(1, 6));
  }

  /** The skipped item's piece goes to UL, which the Y perms swap with UB an even number of times. */
  @Test
  public void blamesASkipWhoseTargetTheCornerAlgorithmsMoveAndPutBack() {
    String scramble = "L2 U2 R2 U B2 D' R2 D B2 L2 F L' D L' R2 U B2 F' R F' D'";
    List<List<String>> made = made(oldPochmann(scramble));
    made.remove(6);
    BlindStepDetector detector = replay(scramble, made, true);

    assertEquals(6, firstRed(detector));
    assertEquals("UR-BD", detector.subStepWantedName(1, 6));
  }

  private static List<List<String>> made(SyntheticTwoCycleSolve solve) {
    List<List<String>> made = new ArrayList<List<String>>();
    for (SyntheticTwoCycleSolve.Shot shot : solve.shots()) {
      made.add(shot.made);
    }
    return made;
  }

  /** Turns made as given, so the drift a skipped M2 would have left is left out too. */
  private static BlindStepDetector replay(String scramble, List<List<String>> made, boolean op) {
    SyntheticTwoCycleSolve solve = new SyntheticTwoCycleSolve();
    solve.scramble(scramble);
    for (List<String> turns : made) {
      solve.make(SyntheticTwoCycleSolve.UR_BUFFER, turns);
    }
    BlindStepDetector detector = new BlindStepDetector();
    detector.setBuffers(op ? "UR" : "DF", "ULB");
    detector.setSwaps(true);
    play(scrambled(scramble), detector, solve.reportedSolve().toArray(new String[0]));
    return detector;
  }

  /** The first algorithm carrying red, counted across the steps, or -1. */
  private static int firstRed(StepDetector detector) {
    int index = 0;
    for (int step = 1; step < detector.stepCount(); step++) {
      for (int part = 0; part < detector.subStepCount(step); part++, index++) {
        if (detector.subStepPieceMarks(step, part).contains(PieceMark.WRONG)) {
          return index;
        }
      }
    }
    return -1;
  }

  /** The parity algorithm of an odd OP solve is one algorithm of its own, and not a mistake. */
  @Test
  public void readsTheParityAlgorithmOfAnOddSolve() {
    Random random = new Random(20260926);
    int odd = 0;
    for (int attempt = 0; attempt < SCRAMBLES && odd < SCRAMBLES / 10; attempt++) {
      String scramble = scramble(random);
      SyntheticTwoCycleSolve solve = oldPochmannCornersFirst(scramble);
      List<String> expected = names(solve);
      int parityAt = 0; // the corner shots come first, and an odd count of them takes the parity
      while (expected.get(parityAt).startsWith("UBL")) {
        parityAt++;
      }
      if (parityAt % 2 == 0) {
        continue;
      }
      odd++;
      BlindStepDetector detector = read(scramble, solve, "UR", "UBL");

      assertEquals(scramble, -1, firstRed(detector));
      assertEquals(scramble, null, detector.getLostReading());
      List<String> read = readNames(detector);
      assertEquals(scramble, expected.size(), read.size());
      assertEquals(scramble, "UFR-UBR + UL-UB", read.get(parityAt));
    }
    assertTrue(odd > 0);
  }

  /** The same, held in y2: the cube reports F and B, R and L swapped, and names stay the solver's. */
  @Test
  public void readsTheParityAlgorithmOfAnOddSolveHeldInY2() {
    Random random = new Random(20260926);
    int odd = 0;
    for (int attempt = 0; attempt < SCRAMBLES && odd < SCRAMBLES / 10; attempt++) {
      String scramble = scramble(random);
      SyntheticTwoCycleSolve solve = oldPochmannCornersFirst(scramble);
      List<String> expected = names(solve);
      int parityAt = 0;
      while (expected.get(parityAt).startsWith("UBL")) {
        parityAt++;
      }
      if (parityAt % 2 == 0) {
        continue;
      }
      odd++;
      BlindStepDetector detector = new BlindStepDetector();
      detector.setBuffers("UR", "UBL");
      detector.setSwaps(true);
      detector.setPickupRotation(CubeRotation.byNotation("y2"));
      play(scrambled(heldInY2(scramble)), detector, heldInY2(moves(solve)));

      expected.set(parityAt, "UFR-UBR + UL-UB");
      assertEquals(scramble, -1, firstRed(detector));
      assertEquals(scramble, expected, readNames(detector));
    }
    assertTrue(odd > 0);
  }

  private static String heldInY2(String moves) {
    return String.join(" ", heldInY2(moves.split(" ")));
  }

  private static String[] heldInY2(String[] moves) {
    String[] held = new String[moves.length];
    for (int i = 0; i < moves.length; i++) {
      char face = moves[i].charAt(0);
      int at = "FBRL".indexOf(face);
      held[i] = (at < 0 ? face : "BFLR".charAt(at)) + moves[i].substring(1);
    }
    return held;
  }

  private static List<String> readNames(StepDetector detector) {
    List<String> names = new ArrayList<String>();
    for (int step = 1; step < detector.stepCount(); step++) {
      for (int part = 0; part < detector.subStepCount(step); part++) {
        names.add(detector.subStepName(step, part));
      }
    }
    return names;
  }

  /**
   * The order OP is taught in: everything memorised up front, so setups keep the algorithm's other
   * pieces in place, corners first, and the Ra perm between the types when the counts are odd.
   */
  static SyntheticTwoCycleSolve oldPochmannCornersFirst(String scramble) {
    SyntheticTwoCycleSolve solve = new SyntheticTwoCycleSolve();
    solve.scramble(scramble);
    solve.shootAll(SyntheticTwoCycleSolve.Y_PERM, SyntheticTwoCycleSolve.ULB_BUFFER, true);
    if (solve.shots().size() % 2 == 1) {
      solve.shoot(SyntheticTwoCycleSolve.RA_PERM, "");
    }
    solve.shootAll(SyntheticTwoCycleSolve.T_PERM, SyntheticTwoCycleSolve.UR_BUFFER, true);
    assertTrue("the synthetic solve did not come out: " + solve.leftOver(), solve.isSolved());
    return solve;
  }

  /** Edges first: the corner algorithm's two edges cancel, the edge one's two corners are still out. */
  static SyntheticTwoCycleSolve oldPochmann(String scramble) {
    SyntheticTwoCycleSolve solve = new SyntheticTwoCycleSolve();
    solve.scramble(scramble);
    solve.shootAll(SyntheticTwoCycleSolve.T_PERM, SyntheticTwoCycleSolve.UR_BUFFER);
    solve.shootAll(SyntheticTwoCycleSolve.Y_PERM, SyntheticTwoCycleSolve.ULB_BUFFER);
    assertTrue("the synthetic solve did not come out: " + solve.leftOver(), solve.isSolved());
    return solve;
  }

  /**
   * Corners first, and not by preference: a Y perm swaps two edges and so absorbs an odd corner
   * count, leaving the edges the even permutation M2 can solve. There is no pure M2 solve.
   */
  static SyntheticTwoCycleSolve m2(String scramble) {
    SyntheticTwoCycleSolve solve = new SyntheticTwoCycleSolve();
    solve.scramble(scramble);
    solve.shootAll(SyntheticTwoCycleSolve.Y_PERM, SyntheticTwoCycleSolve.ULB_BUFFER);
    solve.shootAllM2();
    assertTrue("the synthetic solve did not come out: " + solve.leftOver(), solve.isSolved());
    return solve;
  }

  static BlindStepDetector read(String scramble, SyntheticTwoCycleSolve solve, String edgeBuffer,
      String cornerBuffer) {
    BlindStepDetector detector = new BlindStepDetector();
    detector.setBuffers(edgeBuffer, cornerBuffer);
    detector.setSwaps(true);
    play(scrambled(scramble), detector, moves(solve));
    return detector;
  }

  private static CubieCube scrambled(String scramble) {
    CubieCube cube = new CubieCube();
    for (String token : scramble.split(" ")) {
      applyToken(cube, token);
    }
    return cube;
  }

  static String[] moves(SyntheticTwoCycleSolve solve) {
    return moves(solve.shots());
  }

  private static String[] moves(List<SyntheticTwoCycleSolve.Shot> shots) {
    List<String> moves = new ArrayList<String>();
    for (SyntheticTwoCycleSolve.Shot shot : shots) {
      moves.addAll(shot.reported);
    }
    return moves.toArray(new String[0]);
  }

  private static void play(CubieCube cube, StepDetector detector, String[] moves) {
    SolveAnalyzer analyzer = new SolveAnalyzer(detector);
    long timestampMs = 1000;
    analyzer.start(new CubeState(cube.toFaceCube()), timestampMs);
    analyzer.onState(new CubeState(cube.toFaceCube()));
    timestampMs += 9000;
    for (String token : moves) {
      Face face = Face.valueOf(token.substring(0, 1));
      boolean prime = token.endsWith("'");
      for (int i = 0; i < (token.endsWith("2") ? 2 : 1); i++) {
        cube.applyMove(face, prime);
        analyzer.onMove(new CubeMove(face, prime, timestampMs));
        analyzer.onState(new CubeState(cube.toFaceCube()));
        timestampMs += 100;
      }
    }
  }

  /** What the solve was memorised as, algorithm by algorithm. */
  static List<String> names(SyntheticTwoCycleSolve solve) {
    List<String> names = new ArrayList<String>();
    for (SyntheticTwoCycleSolve.Shot shot : solve.shots()) {
      names.add(shot.name);
    }
    return names;
  }

  /** What the detector called them, in the order it read them. */
  static List<String> read(StepDetector detector) {
    List<String> names = new ArrayList<String>();
    for (int step = 0; step < detector.stepCount(); step++) {
      for (int part = 0; part < detector.subStepCount(step); part++) {
        names.add(detector.subStepName(step, part));
      }
    }
    return names;
  }

  private static String conjugate(String setup, String alg) {
    return setup.isEmpty() ? alg : setup + " " + alg + " " + invert(setup);
  }

  private static String invert(String moves) {
    String[] tokens = moves.trim().split("\\s+");
    StringBuilder inverted = new StringBuilder();
    for (int i = tokens.length - 1; i >= 0; i--) {
      String token = tokens[i];
      inverted.append(inverted.length() > 0 ? " " : "").append(token.endsWith("2") ? token
          : token.endsWith("'") ? token.substring(0, token.length() - 1) : token + "'");
    }
    return inverted.toString();
  }

  private static void applyToken(CubieCube cube, String token) {
    Face face = Face.valueOf(token.substring(0, 1));
    for (int i = 0; i < (token.endsWith("2") ? 2 : 1); i++) {
      cube.applyMove(face, token.endsWith("'"));
    }
  }

  static String scramble(Random random) {
    List<String> moves = new ArrayList<String>();
    String last = "";
    while (moves.size() < 20) {
      String face = FACES[random.nextInt(FACES.length)];
      if (face.equals(last)) {
        continue;
      }
      last = face;
      moves.add(face + SUFFIXES[random.nextInt(SUFFIXES.length)]);
    }
    return String.join(" ", moves);
  }
}
