package com.cube.nanotimer.smartcube.step;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The algorithms F2L cases are usually solved with, for every case {@link F2LCases} names: the 41
 * basic ones and the advanced ones with a piece trapped in another slot. A pair turned with none of
 * them is one worth pointing out.
 *
 * <p>Gathered by hand from published algorithm sheets and committed, never fetched. Every algorithm
 * is written for the pair going into front right with the cross down: a sheet's back-slot algorithm
 * is kept behind the rotation that brings its slot there, since it is often not the front one
 * mirrored. A case's rows are in no particular order.
 *
 * <p>Some basic ones only work with another slot still empty, and say which: they break that slot's pair, so they
 * are usual for the case but not something to show a solver whose slot is filled.
 *
 * <p>{@code F2LCaseAlgorithmsTest} checks that every row solves the case it is filed under and that
 * a basic one disturbs no slot but the one it names, which is what makes taking a table off a
 * website safe.
 */
public final class F2LCaseAlgorithms {

  /** One row per algorithm: the case, the algorithm, and the slot it needs empty ("" for none). */
  private static final String[][] ALGORITHMS = {
    {"1", "U R U' R'", ""},
    {"1", "R' F R F'", ""},
    {"1", "U2 R U2 R'", ""},
    {"1", "M' U R U' r'", ""},
    {"1", "y' r' U' R U M'", ""},
    {"1", "y U F' L F L2 U L", ""},
    {"1", "y2 U' r U B' U' B r'", ""},
    {"2", "y' U' R' U R", ""},
    {"2", "U' F' U F", ""},
    {"2", "F R' F' R", ""},
    {"2", "y U' L' U L", ""},
    {"2", "d' L' U L", ""},
    {"2", "y U r' U' F U F' r", ""},
    {"2", "y2 l U L' U' M'", ""},
    {"2", "y' U2 R' U2 R", ""},
    {"3", "F' U' F", ""},
    {"3", "y' R' U' R", ""},
    {"3", "y L' U' L", ""},
    {"3", "S U R U' R' S'", ""},
    {"3", "y U2 R' F R U R' F' R", ""},
    {"3", "y U S' F U' F' U S", ""},
    {"3", "y2 U' R U B' U' B R'", ""},
    {"3", "y' U2 r' R' F R F' r", ""},
    {"4", "R U R'", ""},
    {"4", "y F U F'", ""},
    {"4", "y' f R f'", ""},
    {"4", "y2 L U L'", ""},
    {"4", "y S' L F' L' f", ""},
    {"4", "y U' M L' U L U' M'", ""},
    {"4", "y2 U f R U R' U2 f' r x'", ""},
    {"5", "U' R U R' U2 R U' R'", ""},
    {"5", "U' R U R' U R' F R F'", ""},
    {"5", "U' R U R' U' R U2 R'", ""},
    {"5", "U F' R' F' R F", "fl"},
    {"5", "U R F R' F' R'", "br"},
    {"5", "F2 L' U' L U F2", ""},
    {"5", "y U R' F r U' r' F' R", ""},
    {"5", "y U2 F R U R' U2 F'", ""},
    {"5", "y' U' R' F R U R' U' F' R", ""},
    {"6", "d R' U' R U2 R' U R", ""},
    {"6", "y' U R' U' R U2 R' U R", ""},
    {"6", "U' r U' R' U R U r'", ""},
    {"6", "y F2 R U R' U' F2", ""},
    {"6", "U' F' R' F R F", "fl"},
    {"6", "U' R F R F' R'", "br"},
    {"6", "y U L' U' L U2 L' U L", ""},
    {"6", "y R' F2 R U R' U' F2 U R", ""},
    {"6", "y U L' U' L U L' U2 L", ""},
    {"6", "y2 U r U' r' U' L U F L'", ""},
    {"6", "y' U2 R' F' U' F U2 R", ""},
    {"7", "U' R U2 R' U2 R U' R'", ""},
    {"7", "U' R U2 R' U' R U2 R'", ""},
    {"7", "M' U' M U2 r U' r'", ""},
    {"7", "U' R U2 R' U R' F R F'", ""},
    {"7", "y F U R U2 R' U F'", ""},
    {"7", "y U' F U2 R U' R' U F'", ""},
    {"7", "y l U2 L2 U' L2 U' l'", ""},
    {"7", "y' F R U R2 U' R F'", ""},
    {"8", "d R' U2 R U2 R' U R", ""},
    {"8", "y' U R' U2 R U2 R' U R", ""},
    {"8", "U R' F R F' R' F R F' R U' R'", ""},
    {"8", "r' U2 R2 U R2 U r", ""},
    {"8", "d R' U2 R U R' U2 R", ""},
    {"8", "y U L' U2 L U2 L' U L", ""},
    {"8", "y U' R' U2 R U R' U R U2 L' U L", ""},
    {"8", "y U L' U2 L U' L F' L' F", ""},
    {"8", "y2 f' L' U' L2 U L' f", ""},
    {"9", "U' R U' R' d R' U' R", ""},
    {"9", "U' R U' R' U F' U' F", ""},
    {"9", "d R' U' R U' R' U' R", ""},
    {"9", "F R U R' U' F' R U' R'", ""},
    {"9", "y F2 U R U' R' F2", ""},
    {"9", "R' U' R F' U' F", "br"},
    {"9", "F U' F2 U' F", "fl"},
    {"9", "y L' U L U' L' U' L U2 L' U L", ""},
    {"9", "y2 y U2 R' U R U R' U' R", ""},
    {"9", "y' U2 r U R' U R' U' R2 U' r'", ""},
    {"10", "U' R U R' U R U R'", ""},
    {"10", "R d' R U R' U2 F'", ""},
    {"10", "U F' U F U' R U R'", ""},
    {"10", "d R' U R d' R U R'", ""},
    {"10", "y2 B2 U' R' U R B2", ""},
    {"10", "F U F' R U R'", "fl"},
    {"10", "R' U R2 U R'", "br"},
    {"10", "U2 R U' R' U' R U R'", ""},
    {"10", "y' U R' U R U' f R f'", ""},
    {"10", "y2 L U' L' U L U L' U2 L U' L'", ""},
    {"11", "U' R U2 R' d R' U' R", ""},
    {"11", "U' R U2 R' U F' U' F", ""},
    {"11", "y' R U2 R2 U' R2 U' R'", ""},
    {"11", "F' U L' U2 L U2 F", ""},
    {"11", "y L' U L U' L' U L U2 L' U L", ""},
    {"11", "y F U R U' R' U R U' R' U F'", ""},
    {"11", "y2 L U2 L' U' l U' l' U2 l U l'", ""},
    {"11", "y' R' U R U' R' U R U R' U2 R", ""},
    {"12", "R U' R' U R U' R' U2 R U' R'", ""},
    {"12", "R U2 R' U2 R U2 R' U2 R U' R'", ""},
    {"12", "R' U2 R2 U R2 U R", ""},
    {"12", "U R U' R' U' R U R' U' R U R'", ""},
    {"12", "R U R' U R' F R F' R U R'", ""},
    {"12", "R' U2 R2 U R'", "br"},
    {"12", "U F' U2 F U' R U R'", ""},
    {"12", "y L' U2 L U l' U l U2 l' U' l", ""},
    {"12", "y2 U2 R' U2 R U2 L U L' U2 R' U R", ""},
    {"12", "y' f R' U R2 U' R2 f'", ""},
    {"12", "y' U R' U2 R M U2 R' U R U M'", ""},
    {"13", "d R' U R U' R' U' R", ""},
    {"13", "y' U R' U R U' R' U' R", ""},
    {"13", "R U' R' U R' F R F' R U' R'", ""},
    {"13", "M' U' R U R' U2 R U' r'", ""},
    {"13", "y y' R U' R' U2 R U' R' U F' U F", ""},
    {"13", "y U L' U L U' L' U L U L' U L", ""},
    {"13", "y U L F' L2 U' L U L F L'", ""},
    {"13", "y2 U L U' L F' L2 U' L U F U L'", ""},
    {"14", "U' R U' R' U R U R'", ""},
    {"14", "F U' F' R U R'", "fl"},
    {"14", "R U2 R' U2 R U R' U2 R U' R'", ""},
    {"14", "U' R2 D R' U R D' R2", ""},
    {"14", "U2 R2 U R' U R U2 R2", ""},
    {"14", "y M' U L' U' L U2 L' U l", ""},
    {"14", "y2 U' L U' L' U L U' L' U' L U' L'", ""},
    {"15", "R' D' R U' R' D R U R U' R'", ""},
    {"15", "F' U F U2 R U R'", ""},
    {"15", "U R' F R F' U R U R'", ""},
    {"15", "R U2 R' U R U R' U R U' R'", ""},
    {"15", "R U R' U2 R U' R' U R U' R'", ""},
    {"15", "R U' R U2 R2 U' R2 U' R2", ""},
    {"15", "U' R2 U2 R U' R' U R' U2 R2", ""},
    {"15", "U2 R U R' U' R U2 R' U R U R'", ""},
    {"15", "U' R' U2 R' U R' U' R U2 R", ""},
    {"15", "U' R' U R U' R U R'", "br"},
    {"15", "U R U' R' D R U' R' D'", "fl"},
    {"15", "R F U F' U' R'", "fl"},
    {"15", "M U r U' r' U' M'", ""},
    {"15", "y F U2 R U R' U F'", ""},
    {"15", "y U L' l U' l' U l U l' U L", ""},
    {"15", "y' R2 F R F' R U R' U2 R", ""},
    {"15", "y' R2 F R F' R U2 R' U R", ""},
    {"16", "R U' R' U d R' U' R", ""},
    {"16", "R U' R' U2 F' U' F", ""},
    {"16", "U R F R U R' U' F' R'", ""},
    {"16", "y' U R U2 R U' R U R' U2 R'", ""},
    {"16", "F' R' U' R U F", "br"},
    {"16", "R U' R' U2 y' R' U' R", ""},
    {"16", "U M' U R U' r' U' R U R'", ""},
    {"16", "U F U R U' R' F' R U R'", ""},
    {"16", "y F U' R U' R' U2 F'", ""},
    {"16", "y L' U' L U2 L' U L U' L' U L", ""},
    {"16", "y L' U2 L U' L' U' L U' L' U L", ""},
    {"16", "y M U' l' U l U M'", ""},
    {"16", "y2 L2 F' L' F L' U2 L U' L'", ""},
    {"16", "y' U2 R' U' R U R D R' U' R D' R'", ""},
    {"16", "y' F R' F' R U2 R' U' R2 U' R'", ""},
    {"17", "R U2 R' U' R U R'", ""},
    {"17", "y2 L U2 L' U' L U L'", ""},
    {"17", "R U R' U' R U2 R' U2 R U R'", ""},
    {"17", "y L F' L' F L' U L U' L' U L", ""},
    {"17", "y L' U2 L U2 l' U L U' L' U' l", ""},
    {"17", "y' R' U2 F R U R' U' F' R", ""},
    {"18", "y' R' U2 R U R' U' R", ""},
    {"18", "y L' U2 L U L' U' L", ""},
    {"18", "R U R' U' R U R' U' F R' F' R", ""},
    {"18", "R' F R F' R U' R' U R U' R'", ""},
    {"18", "F' U2 F U F' U' F", ""},
    {"18", "y2 U F U R U' R' F' L U L'", ""},
    {"18", "y2 L U2 F' L' U' L U F L'", ""},
    {"18", "y2 L U2 L' U2 l U' L' U L U l'", ""},
    {"19", "U R U2 R' U R U' R'", ""},
    {"19", "R U' R' U R U' R' U R U R'", ""},
    {"19", "U R U2 R2 F R F'", ""},
    {"19", "d f R2 f' U f R' f'", ""},
    {"19", "y U L' U L2 F' L' F L' U L", ""},
    {"19", "y' U R' F' U2 F R U R' U' R", ""},
    {"19", "y' U2 f R2 U R2 U' R f'", ""},
    {"20", "y' U' R' U2 R U' R' U R", ""},
    {"20", "U' R U' R2 F R F' R U' R'", ""},
    {"20", "y' R' U R U' R' U R U' R' U' R", ""},
    {"20", "y U' L' U2 L U' L' U L", ""},
    {"20", "U' F' U2 F U' F' U F", ""},
    {"20", "y U' L' U2 L2 F' L' F", ""},
    {"20", "y2 U' L F U2 F' L' U' L U L'", ""},
    {"20", "y2 U' L U L' U l U' l' U2 l U l'", ""},
    {"21", "R U' R' U2 R U R'", ""},
    {"21", "U2 R U R' U R U' R'", ""},
    {"21", "R B U2 B' R'", ""},
    {"21", "y' f R' f' U2 f R f'", ""},
    {"21", "y l' U l U2 l' U' l", ""},
    {"21", "y2 l U' L' U2 L U l'", ""},
    {"21", "y' U2 R' U' R S R f' U' F", ""},
    {"21", "y' U f U R U' R f'", ""},
    {"22", "y' R' U R U2 R' U' R", ""},
    {"22", "y' U2 R' U' R U' R' U R", ""},
    {"22", "r U' r' U2 r U r'", ""},
    {"22", "F' L' U2 L F", ""},
    {"22", "y U2 L' U' L U' L' U L", ""},
    {"22", "y U' L' U L U2 L' U L U' L' U L", ""},
    {"23", "U2 R2 U2 R' U' R U' R2", ""},
    {"23", "U F R' F' R U R U R'", ""},
    {"23", "U R U' R' U' R U' R' U R U' R'", ""},
    {"23", "R U R' U' U' R U R' U' R U R'", ""},
    {"23", "R U' R' U' R U R' U2 R U R'", ""},
    {"23", "R2 U R' U R U2 R' U' R'", ""},
    {"23", "R U R' U2 R U R' U' R U R'", ""},
    {"23", "R U' R2 D' R U2 R' D R", ""},
    {"23", "y F' U' L' U L F L' U L", ""},
    {"23", "y U L' U' L2 F' L' F L' U L", ""},
    {"23", "y F U' R U R' U R U2 R' F'", ""},
    {"23", "y U' F R U' R' F' L' U' L", ""},
    {"23", "y2 L' U' L U' L' U2 L2 U2 L'", ""},
    {"23", "y' U R' F R' F' R2 U' R' U R", ""},
    {"23", "y' U2 l' U' L U' L' U2 B' l", ""},
    {"23", "y' R' F' U' F U2 R U' R' U' R", ""},
    {"23", "y' U R' U' F' U F R U' R' U R", ""},
    {"24", "R U R' d R' U R U' R' U R", ""},
    {"24", "y' R' U' R U U R' U' R U R' U' R", ""},
    {"24", "y' U2 R2 U2 R U R' U R2", ""},
    {"24", "U' R U R2 F R F' R U' R'", ""},
    {"24", "F U R U' R' F' R U' R'", ""},
    {"24", "R U R' U R U R' U' F R' F' R", ""},
    {"24", "R U R' U R U2 R' F' U2 F", ""},
    {"24", "y' R' U' R U2 R' U' R U R' U' R", ""},
    {"24", "U F' L' U L F R U R'", ""},
    {"24", "y U' L' U L U L' U L U' L' U L", ""},
    {"24", "y U' F' r U r' U' L' U' L", ""},
    {"24", "y L' U L U L' U' L U2 L' U' L", ""},
    {"24", "y F U' R U2 R' U R U2 R' F'", ""},
    {"24", "y2 U2 r U R' U R U2 B r'", ""},
    {"24", "y2 U' L F' L F L2 U L U' L'", ""},
    {"24", "y2 U2 F U R U' R' F' U2 L U' L'", ""},
    {"24", "y' R U R' U R U2 R2 U2 R", ""},
    {"25", "U' R' F R F' R U R'", ""},
    {"25", "R' U' R' U' R' U R U R", ""},
    {"25", "U' F' U F U R U' R'", ""},
    {"25", "R' F' R U R U' R' F", ""},
    {"25", "U' F' R U R' U' R' F R", ""},
    {"25", "R U' R' U' R U' R' U R U R'", ""},
    {"25", "U R' U' R' U' R2 U R U R", ""},
    {"25", "U2 R' U' R' U' R U R U R", ""},
    {"25", "R2 U' R' U R2", "br"},
    {"25", "U D' R U' R' D", "br"},
    {"25", "l' U' l U l F' l' F", ""},
    {"25", "y U' L' U L F' r U r'", ""},
    {"25", "y2 R D' R' U' R D R' L U L'", ""},
    {"25", "y2 U' f' L' f U L U L'", ""},
    {"25", "y' U' R' U M U' R U M'", ""},
    {"25", "y' R' S' R U' R' S R", ""},
    {"26", "y' R U R U R U' R' U' R'", ""},
    {"26", "U R U' R' U' F' U F", ""},
    {"26", "U R U' R' F R' F' R", ""},
    {"26", "y' U' R U R U R2 U' R' U' R'", ""},
    {"26", "y' U2 R U R U R' U' R' U' R'", ""},
    {"26", "r U r' U2 r U r' U2 r U' r'", ""},
    {"26", "U l F' l' F R' F' R", ""},
    {"26", "d R B' R' B R' U' R", ""},
    {"26", "R S' R' U R S R'", ""},
    {"26", "U R U R' U' y L' U' L", ""},
    {"26", "y r U r' U' r' F r F'", ""},
    {"26", "y U F L' U' L U L F' L'", ""},
    {"26", "y2 F R2 u R u' R2 F'", ""},
    {"26", "y2 U' R u R' U R U' u' R'", ""},
    {"26", "y2 R E' R' U R E R'", ""},
    {"26", "y' R' U R U R' U R U' R' U' R", ""},
    {"26", "y' U' R S2 R' U' R S2 R'", ""},
    {"27", "R U' R' U R U' R'", ""},
    {"27", "R U' R2 F R F'", ""},
    {"27", "F' U' F U2 R U' R'", ""},
    {"27", "y' f R' f' U f R' f'", ""},
    {"27", "y' f R' f' r' U' R U M'", ""},
    {"27", "y L' U' L U F' r U r'", ""},
    {"27", "y U' F R U2 R' U F'", ""},
    {"27", "y' R' U2 R' F R F' R", ""},
    {"27", "y' R' U' R U r' U' R U M'", ""},
    {"28", "R U R' U' F R' F' R", ""},
    {"28", "R U R' d R' U2 R", ""},
    {"28", "y L' U L U' L' U L", ""},
    {"28", "y' R' U R U' R' U R", ""},
    {"28", "R U R' U F' U2 F", ""},
    {"28", "F' U F U' F' U F", ""},
    {"28", "y L' U L2 F' L' F", ""},
    {"28", "y2 L U2 L F' L' F L'", ""},
    {"28", "y2 L U L' U' l U L' U' M'", ""},
    {"28", "y2 L U2 L' U f' L f", ""},
    {"29", "y' R' U' R U R' U' R", ""},
    {"29", "U2 R U' R' y' R' U' R", ""},
    {"29", "R' F R F' R' F R F'", ""},
    {"29", "R' F R F' U R U' R'", ""},
    {"29", "y L' U' L U L' U' L", ""},
    {"29", "y U L' U2 L U2 L' U' L", ""},
    {"29", "y U F' L F L2 U' L", ""},
    {"30", "R U R' U' R U R'", ""},
    {"30", "U2 F' U F R U R'", ""},
    {"30", "U' R U2 R' U2 R U R'", ""},
    {"30", "U' F R' F' R2 U R'", ""},
    {"30", "y L F' L' F U' L' U L", ""},
    {"30", "y U' F U' R U2 R' F'", ""},
    {"31", "R U' R' d R' U R", ""},
    {"31", "R U' R' U F' U F", ""},
    {"31", "U' R' F R F' R U' R'", ""},
    {"31", "R U2 R' U' F R' F' R", ""},
    {"31", "R U' R' U y' R' U R", ""},
    {"31", "F' U F R U2 R'", ""},
    {"31", "R U' R' U y L' U L", ""},
    {"31", "y U L F' L' F L' U L", ""},
    {"31", "y L' U L U' y L U' L'", ""},
    {"31", "y2 L U' L F' L' F L'", ""},
    {"31", "y2 L U2 L' U' l U L' U' M'", ""},
    {"31", "y' R' U R' F R F' R", ""},
    {"32", "R U R' U' R U R' U' R U R'", ""},
    {"32", "U R U' R' U R U' R' U R U' R'", ""},
    {"32", "U' R U R' U' R U R' U R U' R'", ""},
    {"32", "R2 U R2 U R2 U2 R2", ""},
    {"32", "U' F R' F' R U' R U R'", ""},
    {"32", "y U' L' U L U' L' U L U' L' U L", ""},
    {"32", "y U L' U L U' L' U2 L U L' U' L", ""},
    {"32", "y U2 F U' R U R' U F'", ""},
    {"32", "y L' U' L U L' U' L U L' U' L", ""},
    {"32", "y2 U' L U' L' U L U2 L' U' L U L'", ""},
    {"32", "y' R2 U' R2 U' R2 U2 R2", ""},
    {"33", "U' R U' R' U2 R U' R'", ""},
    {"33", "y U' L' U' L U2 L' U' L", ""},
    {"33", "u R U' R' u'", "br"},
    {"33", "E F' U' F u", "fl"},
    {"33", "y R' D R U' R' D' R", ""},
    {"33", "R U R' U' R U' R' U R U' R'", ""},
    {"33", "U' R U' R' U' R U2 R'", ""},
    {"33", "y U L' U2 L U' L' U' L", ""},
    {"33", "y U' L D L' U L D' L'", ""},
    {"33", "y2 D' R D R' U R D' R' D", ""},
    {"33", "y' U R D R' U' R D' R'", ""},
    {"34", "U F' U F U2 F' U F", ""},
    {"34", "U' R U2 R' U R U R'", ""},
    {"34", "U R U R' U2 R U R'", ""},
    {"34", "d R' U R U2 R' U R", ""},
    {"34", "y U L' U L U2 L' U L", ""},
    {"34", "U y F U2 R U2 R' F'", ""},
    {"34", "E' R U R' E", "br"},
    {"34", "u' F' U F u", "fl"},
    {"34", "U R' D' R U' R' D R", ""},
    {"34", "y U L' U L U L' U2 L", ""},
    {"34", "y L' U' L U L' U L U' L' U L", ""},
    {"34", "y2 U2 R D' R' U' R D R'", ""},
    {"34", "y' U R2 F R F' R U' R' U R", ""},
    {"35", "U' R U R' U F' U' F", ""},
    {"35", "U' R U R' d R' U' R", ""},
    {"35", "U2 R U' R' U' F' U' F", ""},
    {"35", "U2 R U R' F R' F' R", ""},
    {"35", "U' R U R' U y' R' U' R", ""},
    {"35", "y U2 F U F' U' L' U L", ""},
    {"35", "y U2 L F' L' F U2 L' U' L", ""},
    {"35", "y U' F R' F R F' U F'", ""},
    {"35", "y2 U2 L U L' U' L F U F' L'", ""},
    {"35", "y2 L U L' y R' U' R U R' U' R", ""},
    {"35", "y2 U2 L U M U L' U' M'", ""},
    {"35", "y' R' F R' F' R U R U' R' U' R", ""},
    {"35", "y' U' R' F' U F U' R U R' U' R", ""},
    {"36", "U F' U' F U' R U R'", ""},
    {"36", "U2 R' F R F' U2 R U R'", ""},
    {"36", "y' U R' U' R U' y R U R'", ""},
    {"36", "R U R' U R U R' U' F' U' F", ""},
    {"36", "R2 u R U R' U' u' R' U R'", ""},
    {"36", "y U2 L' U L U F U F'", ""},
    {"36", "y U2 L' U' L F' r U r'", ""},
    {"36", "y2 U2 f' L' f U L U' L'", ""},
    {"36", "y2 L F' L F L' U' L' U L U L'", ""},
    {"36", "y' U2 R' U' R U R' F' U' F R", ""},
    {"37", "R' F R F' R U' R' U R U' R' U2 R U' R'", ""},
    {"37", "R U' R' d R' U2 R U2 R' U R", ""},
    {"37", "R U R' U2 R U2 R' d R' U' R", ""},
    {"37", "R2 U2 F R2 F' U2 R' U R'", ""},
    {"37", "R U R' U' R U2 R' d R' U' R U' R' U R", ""},
    {"37", "R U' R2 U2 R U' F' U F", "br"},
    {"37", "R U' R2 U2 R F R' F' R", "br"},
    {"37", "R U' R2 U2 R U2 F' U2 F", "br"},
    {"37", "R U2 R' U R U2 R' U F' U' F", ""},
    {"37", "R U R' U2 R U2 R' U y' R' U' R", ""},
    {"37", "y L2 U2 F' L2 F U2 L U' L", ""},
    {"37", "y L' U2 L U' L' U2 L U' F U F'", ""},
    {"37", "y L' U' L U2 L' U2 L U' y' R U R'", ""},
    {"37", "y R' F R L' U' L U' R' F R L' U' L", ""},
    {"37", "y2 L U' L' l' U2 L2 U L2 U l", ""},
    {"37", "y2 f' L f U' L U2 L' U2 L U' L'", ""},
    {"37", "y2 L' f U f' L' U2 L2 U L2 U L", ""},
    {"37", "y' R' U R r U2 R2 U' R2 U' r'", ""},
    {"37", "y' R' U R f R U R2 U' R f'", ""},
    {"38", "R U' R' U' R U R' U2 R U' R'", ""},
    {"38", "y' R' U' R U2 R' U R U' R' U' R", ""},
    {"38", "R U R' U' R U2 R' U' R U R'", ""},
    {"38", "R2 U2 R' U' R U' R' U2 R'", ""},
    {"38", "R U' R' U' R U R' U' R U2 R'", ""},
    {"38", "y L' U L U' L' U2 L U' L' U L", ""},
    {"38", "y F R U2 R' U' R U R' U2 F'", ""},
    {"38", "y L' U2 L' U' L U' L' U2 L2", ""},
    {"38", "y F U' R U2 R' U' R U2 R' F'", ""},
    {"39", "R U' R' U R U2 R' U R U' R'", ""},
    {"39", "R U R' U2 R U' R' U R U R'", ""},
    {"39", "R U2 R U R' U R U2 R2", ""},
    {"39", "y' R2 U2 R U R' U R U2 R", ""},
    {"39", "R U2 R' U R U' R' U R U R'", ""},
    {"39", "y L' U' L U L' U2 L U L' U' L", ""},
    {"39", "y F' L F L2 U2 L U L' U' L", ""},
    {"39", "y L' U L U L' U' L U2 L' U L", ""},
    {"39", "y F U2 R U' R' U R U2 R' F'", ""},
    {"39", "y' f R2 U R' U' F R' f' U F'", ""},
    {"40", "r U' r' U2 r U r' R U R'", ""},
    {"40", "R U' R' d R' U' R U' R' U' R", ""},
    {"40", "R U' R' U' R U' R' d R' U' R", ""},
    {"40", "R F U R U' R' F' U' R'", ""},
    {"40", "R U' R2 U' R y' R' U' R y", "br"},
    {"40", "F' L' U2 L F R U R'", ""},
    {"40", "R U' R' F R U R' U' F' R U' R'", ""},
    {"40", "R U' R' U' R U' R' U y' R' U' R", ""},
    {"40", "y L' U L F R U2 R' F'", ""},
    {"40", "y L' U L l' U l U2 l' U' l", ""},
    {"40", "y L' U L U2 y L U L' U L U' L'", ""},
    {"40", "y2 f' L f U2 L U L' U2 L U2 L'", ""},
    {"40", "y' R2 F' U' F U R U' R", ""},
    {"41", "R U' R' r U' r' U2 r U r'", ""},
    {"41", "R U' R' U d R' U' R U' R' U R", ""},
    {"41", "R U' R' U2 y' R' U' R U' R' U R", ""},
    {"41", "R U R' U' R U' R' U2 F' U' F", ""},
    {"41", "R U F R U R' U' F' R'", ""},
    {"41", "y' R' U R2 U R' y R U R'", "fl"},
    {"41", "R U' R' F' L' U2 L F", ""},
    {"41", "R U R' U' y M U' R' F R U M'", ""},
    {"41", "R U R' U' R U' R' U2 y' R' U' R", ""},
    {"41", "y l' U l U2 l' U' l L' U' L", ""},
    {"41", "y L' U L U L' U L U' y' R U R'", ""},
    {"41", "y F R U2 R' F' L' U' L", ""},
    {"41", "y2 f' L f U' L U L' U L U L'", ""},
    {"41", "y2 L2 F U F' U' L' U L'", ""},
    {"41", "y' R' U R' U' F' U F R2", ""},
    {"41", "y' f R' f' U2 R' U' R U2 R' U2 R", ""},
    {"a1", "y' S R' S'", ""},
    {"a1", "y' R U' R' y R U' R'", ""},
    {"a1", "y' R U' R' U R2 F R F' R", ""},
    {"a1", "L' U' L U R U' R'", ""},
    {"a1", "y2 y R U' R2 F' U' F R", ""},
    {"a2", "y2 L F' U2 F L'", ""},
    {"a2", "y2 R U' R' L U2 L'", ""},
    {"a2", "y2 L R U' R' U2 L'", ""},
    {"a2", "y2 F' L U2 L' F", ""},
    {"a2", "y' L' U' L y R U' R'", ""},
    {"a2", "L U' L' U' R U' R'", ""},
    {"a3", "y R U' R' U F' r U r'", ""},
    {"a3", "y y' R' U2 R2 U' R'", ""},
    {"a3", "y R U' F R' U R F' R'", ""},
    {"a3", "y2 L' U' L2 U2 L'", ""},
    {"a3", "y' y R' U' R U' R U' R'", ""},
    {"a3", "y' L U' L' y' U2 L U' L'", ""},
    {"a4", "y' F R' F' R U R' U2 R", ""},
    {"a4", "y' R U R' U2 f R f'", ""},
    {"a4", "y' R U R' U2 S U' R' U R S'", ""},
    {"a4", "y' y U2 L' U L U' R U R'", ""},
    {"a4", "U' F U' R U R2 F' R", ""},
    {"a5", "y2 R U R' U L U L'", ""},
    {"a5", "y2 U' R U2 M' B r'", ""},
    {"a5", "y2 y U2 L' U L U2 f R f'", ""},
    {"a5", "y' r U' r' F R' U2 R", ""},
    {"a6", "y R U R' F U F'", ""},
    {"a6", "y F R' F' R L' U L", ""},
    {"a6", "y2 U2 L' U L U L U L'", ""},
    {"a6", "y2 L' U L U L' U' L2 U L'", ""},
    {"a7", "y' U' F' U' f R S'", ""},
    {"a7", "y' y U' L' U' L R U R'", ""},
    {"a7", "y' R U' R' U' R U' R' f R f'", ""},
    {"a7", "y' F R' F' U R U' R' U' R", ""},
    {"a7", "U' L' U L R U' R'", ""},
    {"a8", "y2 U' F' U2 L U L' F", ""},
    {"a8", "y2 U' R' F R F' U2 L U L'", ""},
    {"a8", "y2 y' U R' U2 R F U F'", ""},
    {"a8", "y2 R U' R' U L U' L' U L U L'", ""},
    {"a8", "y' F U2 R U R2 U' R F'", ""},
    {"a8", "y' U' L' U L y' L U2 L'", ""},
    {"a8", "y' U' L' U' L d' R U R'", ""},
    {"a8", "R D' R' U R U D R'", ""},
    {"a8", "y U' R' U R d' L U' L'", ""},
    {"a8", "y U' R' U R U2 F' r U r'", ""},
    {"a9", "y y' U R' U2 R U' R U R'", ""},
    {"a9", "y U R' F' R F' R' F R", ""},
    {"a9", "y U R' F R F' R U' R' U' L' U' L", ""},
    {"a9", "y2 U' L' U L U2 L U' L'", ""},
    {"a9", "y2 y' U' R' F R F' U F U F'", ""},
    {"a9", "y2 U' L' U L U' L U2 L'", ""},
    {"a10", "y' U' R U R2 U' R", ""},
    {"a10", "y' y L' U L R U' R' U R U R'", ""},
    {"a10", "y' U2 R U R' U2 R' U R", ""},
    {"a10", "y' y U' L F2 L' F2", ""},
    {"a11", "y2 U' R U' R' L U' L'", ""},
    {"a11", "y2 U' R U' R' U L U2 L'", ""},
    {"a11", "y' U' L' U' L R' U' R", ""},
    {"a11", "y' U L' U2 L U R' U' R", ""},
    {"a11", "y' U' L' U' R' U' R L", ""},
    {"a12", "y U2 R U R' L' U L", ""},
    {"a12", "y U' R U R2 F R U F'", ""},
    {"a12", "y U' R U R' U2 L' U' L", ""},
    {"a12", "y F U' F' U2 R U' R' L' U' L", ""},
    {"a12", "y2 U' L U L2 U' L2 U L'", ""},
    {"a12", "y2 L' U' L U' L' U L U' L U2 L'", ""},
    {"a12", "y2 U' L S U2 S' L'", ""},
    {"a12", "y2 y' U' R U R2 F R U R' F' R", ""},
    {"a12", "y' U2 L U' L' R' U' R", ""},
    {"a12", "U2 R U2 R2 U' R2 U R'", ""},
    {"a13", "y' U R' F R F' R' U' R", ""},
    {"a13", "y' U R U' R' U S R' S'", ""},
    {"a13", "y' U R U' R' U R U' R' f R' f'", ""},
    {"a13", "U' L F' L2 U L U2 F", ""},
    {"a13", "U' L F' L' F U2 R U R'", ""},
    {"a13", "y2 U' R B' R2 U R U2 R B R'", ""},
    {"a14", "y2 U' F R' F' R U L U L'", ""},
    {"a14", "y2 U2 r2 U B2 U' r2", ""},
    {"a14", "y2 U R U' R' U R U' R' L U2 L'", ""},
    {"a14", "y' U2 R2 D' F2 D R2", ""},
    {"a14", "y' U' L' U L U' L' U L R' U2 R", ""},
    {"a14", "y' L' U' L U L' U' L U' R' U' R", ""},
    {"a14", "L U L' U' L U L' U R U R'", ""},
    {"a15", "y U R' F R2 U' R' U2 F'", ""},
    {"a15", "y U R' F R F' U2 L' U' L", ""},
    {"a15", "y R U R' U' R U R' F U F'", ""},
    {"a15", "y U R' F R2 U' R' U2 R' F' R", ""},
    {"a15", "y2 U' L F' L' F L U L'", ""},
    {"a15", "y2 U' L' U L U' S' L S", ""},
    {"a15", "y' U' R' U' R2 u R u' R'", ""},
    {"a16", "y' U' F' R' U' R F", ""},
    {"a16", "y' d' R' u' R' u R", ""},
    {"a16", "y' U' R U' R' r' U' R U M'", ""},
    {"a16", "y' U' R U' R' B' R B R'", ""},
    {"a16", "y2 U' R' U' R y U R' U' R", ""},
    {"a16", "y' U' R U' R' U f R' f'", ""},
    {"a16", "U L' U2 L y U2 L' U' L", ""},
    {"a17", "y2 U2 R B' U' B R'", ""},
    {"a17", "y2 U' R U R' U' f' L' f", ""},
    {"a17", "y' U2 F U' F' U R' U' R", ""},
    {"a17", "y' U2 L F' L' F R' U' R", ""},
    {"a17", "y' U2 F U F' R' U2 R", ""},
    {"a17", "U2 R d' R' U R F'", ""},
    {"a18", "y U F' U2 F L' U' L", ""},
    {"a18", "y U r' F' D' F D r", ""},
    {"a18", "y U' R U' R' F U2 F'", ""},
    {"a18", "y U' R U' R' U2 F' L F L'", ""},
    {"a18", "y2 U' L' U' L d' R' U' R", ""},
    {"a18", "y2 F U R U' R' U' R U' R' L U2 L' F'", ""},
    {"a18", "y' U' L U' L' d' R U' R'", ""},
    {"a18", "y' U' L U' L' R2 F R F' R", ""},
    {"a18", "y U' F' U2 L' U' L2 F L'", ""},
    {"a19", "y' U' R U2 R' f R f'", ""},
    {"a19", "y' R' F R F' R U2 R2 U R", ""},
    {"a19", "y' U R U R' U y R U R'", ""},
    {"a19", "U' R U F U' F' R'", ""},
    {"a19", "U F U2 R U R2 F' R", ""},
    {"a19", "U L' U L F' U2 F", ""},
    {"a19", "y2 U R' U R d L' U L", ""},
    {"a20", "y2 U R U R' L U L'", ""},
    {"a20", "y2 U' R U2 R' U' L U L'", ""},
    {"a20", "y' U L' U L R' U R", ""},
    {"a21", "y U R F U F' R'", ""},
    {"a21", "y U L u L u' L'", ""},
    {"a21", "y U R U R' U' F U F'", ""},
    {"a21", "y2 U L' U L R B L' B' M' x'", ""},
    {"a21", "y2 U L' U L B L' B' L", ""},
    {"a21", "y' U' L U2 L' y' U2 L U L'", ""},
    {"a21", "U R' U R U' F' U F", ""},
    {"a22", "y' R U' R2 U R", ""},
    {"a22", "y' y M F2 M'", ""},
    {"a22", "y' R U2 R2 U2 R", ""},
    {"a22", "L' U L U2 R U' R'", ""},
    {"a22", "F2 R' F2 R", ""},
    {"a23", "y2 L F' U F L'", ""},
    {"a23", "y2 l F' U L' U' M'", ""},
    {"a23", "y2 R U2 R' y' L' U L", ""},
    {"a23", "y' R' F U' F' R", ""},
    {"a23", "y' r' F U' R U M'", ""},
    {"a23", "y' L' U L y' U L U' L'", ""},
    {"a23", "R u R' U R u' R'", ""},
    {"a23", "L U' L' d' L' U L", ""},
    {"a23", "y L' u' L U' L' u L", ""},
    {"a24", "y R U' R' U2 L' U L", ""},
    {"a24", "y M F2 M'", ""},
    {"a24", "y F2 r U2 r'", ""},
    {"a24", "y U F r U2 r' F'", ""},
    {"a24", "y2 L' U L2 U' L'", ""},
    {"a24", "R' U2 R2 U2 R'", ""},
    {"a25", "y' R' F R F' U R' U2 R", ""},
    {"a25", "y' F' U R' U2 R F", ""},
    {"a25", "y' R U' R' U' f R f'", ""},
    {"a25", "y' R U R' U' B U' B'", ""},
    {"a25", "R' F R2 U' R2 F' R", ""},
    {"a25", "R' F R2 U R' F' R U2 R'", ""},
    {"a25", "F R U' R2 F' R", ""},
    {"a25", "L F' L' F R U' R'", ""},
    {"a25", "y L U L' F U2 F'", ""},
    {"a25", "y2 R' U R d' R' U' R", ""},
    {"a25", "y2 R' U' R l U L' U' M'", ""},
    {"a26", "L R U2 R' L'", ""},
    {"a26", "y2 R U' R' U2 L U L'", ""},
    {"a26", "y2 R U2 R' U L U' L'", ""},
    {"a26", "y2 R U R' U' L U2 L'", ""},
    {"a26", "y' L' U' L U R' U2 R", ""},
    {"a26", "y L' R' U2 R L", ""},
    {"a26", "y R' U' R U2 L' U L", ""},
    {"a27", "y R' F R2 U R' F'", ""},
    {"a27", "y R U2 R' F U' F'", ""},
    {"a27", "y R' F R2 U R2 F' R", ""},
    {"a27", "y R U R' F' r U r'", ""},
    {"a27", "y2 L' U L U f' L' f", ""},
    {"a27", "y2 L' U' L U y' L' U L", ""},
    {"a27", "y2 L' U' L y R' U2 R", ""},
    {"a27", "y2 F U' L U2 L' F'", ""},
    {"a27", "y' L U L' U y R U' R'", ""},
    {"a27", "y' L U' L' U f R f'", ""},
    {"a27", "F' R' U2 R U' F", ""},
    {"a28", "y' R U' R2 U' R U' R' U' R", ""},
    {"a28", "y' R U' R' U' R U' R2 U' R", ""},
    {"a28", "y' r U' r' U2 r U r' d' R U R'", ""},
    {"a28", "y' u R U R' u' R U' R2 U R", ""},
    {"a28", "L' U L U R U R' U R U' R'", ""},
    {"a28", "F U' R U R' U R U' R' F' R U' R'", ""},
    {"a29", "y2 F' U L' U L U' L U L' F", ""},
    {"a29", "y2 R U' R' U' R U' R' d' R' U' R", ""},
    {"a29", "y2 R U' R' y R' U R U R' U' R", ""},
    {"a29", "y2 F' U F L U L' U L U' L'", ""},
    {"a29", "y' L' U L B L' B L B2", ""},
    {"a29", "y' L' U' L U L' U L f R f'", ""},
    {"a29", "f' L f R U R2 F R F'", ""},
    {"a30", "y R U' R' U' L' U L U L' U' L", ""},
    {"a30", "y R U' R' U' R U' R' U2 L' U' L", ""},
    {"a30", "y M F M' U L' U L U' L' U L", ""},
    {"a30", "y r U' r' U2 r U r' d R U R'", ""},
    {"a30", "y2 L' U L U' L U L' U L U' L'", ""},
    {"a31", "y' R U R' U' R U' R' U R' U' R", ""},
    {"a31", "y' R U' R' U R' U' R U' R' U R", ""},
    {"a31", "R' F R U' R' F' R2 U R' U R U R'", ""},
    {"a31", "L' U L U L' U L U2 R U R'", ""},
    {"a31", "L' U L U R U' R' U' R U R'", ""},
    {"a32", "y2 R U R' U' R U' R' f' L' f", ""},
    {"a32", "y2 R U' R' U f' U' L' U L' f", ""},
    {"a32", "y2 R U R' F R U R' U' F' L U2 L'", ""},
    {"a32", "y2 R U' R' y R' U' R U' R' U R", ""},
    {"a32", "y' F U' R U' R' U R' U' R F'", ""},
    {"a32", "y' L' U L y' L U' L' U' L U L'", ""},
    {"a32", "y' L' U L U L' U L U f R f'", ""},
    {"a32", "L U' L' F' L F' L' F2", ""},
    {"a32", "y R' U R U' L' U L d' L U L'", ""},
    {"a33", "y R U' R' U' L' U' L U' L' U L", ""},
    {"a33", "y R U R' U' R U' R' U' L' U' L", ""},
    {"a33", "y R U' R' F' r' F' r2 U r'", ""},
    {"a33", "y y' R' U R2 U R' U R U R'", ""},
    {"a33", "y2 L' U L U L' U L2 U L'", ""},
    {"a34", "y' F' R' U R U' R' U' R F", ""},
    {"a34", "y' R U' R' U' R U R' U f R' f'", ""},
    {"a34", "y' R U' R' U' R U R' r' U' R U M'", ""},
    {"a34", "y' R U' R2 f' U' f R", ""},
    {"a34", "L' U' L U y' R' U R U' R' U' R", ""},
    {"a34", "L' U L y' U2 R' U2 R U' R' U R", ""},
    {"a34", "F U' R U' R' F' R U' R' U' R U R'", ""},
    {"a34", "y L U L' y U2 L U2 L' U' L U L'", ""},
    {"a34", "y L U' L' U' L U L' F' L F L'", ""},
    {"a35", "y2 R U' R' U' R U R' L U' L'", ""},
    {"a35", "y2 R U R' U' R U2 R' U L U L'", ""},
    {"a35", "y2 R U2 R' L U2 L' U' L U L'", ""},
    {"a35", "y' L' U' L R' U R U' R' U' R", ""},
    {"a35", "y' L' U L U R' U2 R U' R' U R", ""},
    {"a35", "L U L' U R U2 R' U' R U R'", ""},
    {"a36", "y R' F R2 U' R' U' R U R' U2 F'", ""},
    {"a36", "y R' F R F' U2 L' U L U' L' U' L", ""},
    {"a36", "y R U' R' U' R U R' U' F U' F'", ""},
    {"a36", "y R U' R' U' R U R' F U2 F'", ""},
    {"a36", "y2 L' U' L d' R' U R U' R' U' R", ""},
    {"a36", "y2 L' U L y R' U2 R U' R' U R", ""},
    {"a36", "y2 F U L U2 L' U' L U L' F'", ""},
    {"a36", "y' L U L' y' L U2 L' U' L U L'", ""},
    {"a36", "y' L U' L' R' F R U R' U' F' R", ""},
    {"a36", "R' U2 R y' R' U R U' R' U' R", ""},
    {"a36", "R' U R U' R' U2 L F' R2 U' R2 U F L' R", ""},
    {"a36", "R' U R2 U' R2 F R F' R U' R'", ""},
    {"a37", "y' R U R' U2 R U' R' f R f'", ""},
    {"a37", "y' F' U' R' U2 R U R' U' R F", ""},
    {"a37", "y' R U' R' y R U2 R' U R U' R'", ""},
    {"a37", "y' R U' R' U R U2 R' y R U' R'", ""},
    {"a37", "L' U' L y' R' U2 R U R' U' R", ""},
    {"a37", "L' U L U L' U' L y' R' U2 R", ""},
    {"a37", "F U2 R U' R' F' U R U R'", ""},
    {"a37", "y L U L' y U L U' L' U L U L'", ""},
    {"a38", "y2 R U' R' U R U2 R' L U2 L'", ""},
    {"a38", "y2 R U' R' U' L U2 L' U L U' L'", ""},
    {"a38", "y2 R U R' L U' L' U L U L'", ""},
    {"a38", "y2 R U' R' U R U2 R' U' L U' L'", ""},
    {"a38", "y' L' U L U L' U' L R' U R", ""},
    {"a38", "y' F U2 R U' R' f R f' F'", ""},
    {"a38", "y' L' U2 L R' U2 R U R' U' R", ""},
    {"a38", "y R' U' R U' L' U2 L U L' U' L", ""},
    {"a39", "y R U R' d' L U' L' U L U L'", ""},
    {"a39", "y R U R' L' U L U' L F' L' F L' U L", ""},
    {"a39", "y R U' R' y' U2 R U2 R' U R U' R'", ""},
    {"a39", "y2 F L U' L' U L U L' F'", ""},
    {"a39", "y2 L' U L l U' L' U L U l'", ""},
    {"a39", "y2 L' U' L y U2 R' U2 R U R' U' R", ""},
    {"a39", "y' f' L f U2 R' U' R U R' U2 R", ""},
    {"a40", "y' R U' R2 U2 R U R' U2 R", ""},
    {"a40", "y' R U' R2 U2 R U2 R' U R", ""},
    {"a40", "y' F R' F' R U' R U2 R2 U' R", ""},
    {"a40", "y' R' F R F' R U' R' U R U' R' U y R U' R'", ""},
    {"a40", "F2 R' F2 D' R U' R' D R", ""},
    {"a40", "L' U' L R U' R' U R U' R' U2 R U' R'", ""},
    {"a40", "L' U' L R' U2 R2 U R2 U R", ""},
    {"a40", "L' U L U2 R U2 R' U2 R U' R'", ""},
    {"a41", "y2 R U' R' d R' U2 R L' U L", ""},
    {"a41", "y2 F' U2 L' U2 L2 U L' F", ""},
    {"a41", "y2 R U' R' y U' R' U2 R U R' U2 R", ""},
    {"a41", "y' F U2 R U2 R2 U' R F'", ""},
    {"a41", "y' L' U L U2 r U2 R2 U' R2 U' r'", ""},
    {"a41", "L U L' R U2 R' y' U R' U' R", ""},
    {"a41", "y R' U R y' U R U2 R' U2 R U' R'", ""},
    {"a41", "y R' U' R L' U2 L y U' L U L'", ""},
    {"a42", "y R U' R' U2 L' U2 L U2 L' U L", ""},
    {"a42", "y y' R' U R2 U2 R' U2 R U' R'", ""},
    {"a42", "y y' R' U R2 U2 R' U' R U2 R'", ""},
    {"a42", "y R' F R F' R U' R' U R U' R' d' L U' L'", ""},
    {"a42", "y2 L' U' L F' U' L F' L' F L U L' F", ""},
    {"a42", "y' L U L' R U2 R2 U' R2 U' R'", ""},
    {"a42", "R' U R2 U2 R' U R' F R F'", ""},
    {"a42", "R' U' R U2 R' U2 R2 U R'", ""},
    {"a1a", "y' U2 R U' R' U' R' U' R", ""},
    {"a1a", "y' U' R U R2 U' R U' R' U R", ""},
    {"a1a", "y' R' F R F' y R U' R'", ""},
    {"a1a", "y' F' U' F R' U' R", ""},
    {"a1a", "U L' U' F' U' F L", ""},
    {"a2a", "y2 R' F R F' L U2 L'", ""},
    {"a2a", "y2 R' F R F' U' L U' L'", ""},
    {"a2a", "y2 U2 R U' R' U2 B' U' B", ""},
    {"a2a", "y2 F' U' F U' y2 F' U' F", ""},
    {"a3a", "y R' F R2 U' R' U F'", ""},
    {"a3a", "y R' F R F' d R' F R F'", ""},
    {"a3a", "y F' U' F U2 L' U' L", ""},
    {"a3a", "y U2 R U' R' U L' U' L", ""},
    {"a3a", "y2 F' L F L' U2 L U' L'", ""},
    {"a4a", "y' U R U R2 U2 R", ""},
    {"a4a", "y' U R U' R' S R2 S'", ""},
    {"a4a", "U L' U L y' U2 R' U R", ""},
    {"a4a", "U L' U L U' F R' F' R", ""},
    {"a4a", "y2 U R' U R y U R' U2 R", ""},
    {"a5a", "y2 y U L' U L R' U2 R", ""},
    {"a5a", "y2 U l U' F2 U l'", ""},
    {"a5a", "y2 U R U R' y R' U R", ""},
    {"a6a", "y U R L' U L R'", ""},
    {"a6a", "y y U L' U L f' L f", ""},
    {"a6a", "y U R U R' U' L' U L", ""},
    {"a7a", "y' U2 R U' R' U2 R' U R", ""},
    {"a7a", "y' R U2 R' U R' U' R", ""},
    {"a7a", "y' U2 R U' R' U R' U2 R", ""},
    {"a7a", "y' U2 R U R' U2 R' U' R", ""},
    {"a7a", "L F L' F L F' L'", ""},
    {"a7a", "U2 L F' L' F y' U' R' U' R", ""},
    {"a8a", "y2 U2 R U' R' d L' U L", ""},
    {"a8a", "y2 R U2 R' f' L' f", ""},
    {"a8a", "y2 U2 R U' R' y R' U2 R", ""},
    {"a8a", "y' U2 L F' L' F U2 R' U' R", ""},
    {"a8a", "y' U R' D R U' R' U' D' R", ""},
    {"a8a", "y' U2 F U2 R' U' R F'", ""},
    {"a8a", "y U2 f R f' U L' U' L", ""},
    {"a9a", "y U2 R U' R' L' U L", ""},
    {"a9a", "y R U2 R' U' L' U' L", ""},
  };

  private F2LCaseAlgorithms() {
  }

  /** The algorithms for a case, as {@link F2LCases} names it. */
  public static List<Algorithm> forCase(String pairCase) {
    List<Algorithm> algorithms = new ArrayList<>();
    for (String[] row : ALGORITHMS) {
      if (row[0].equals(pairCase)) {
        algorithms.add(new Algorithm(row[1], row[2].isEmpty() ? null : row[2]));
      }
    }
    return Collections.unmodifiableList(algorithms);
  }

  /**
   * Which of the case's algorithms an execution was, or null for none of them. Compared as
   * {@link AlgorithmForm}s from every grip, so a back slot's pair, a regrip, the turn that set the
   * pair up and moves turned and taken back all read as the algorithm they surround.
   *
   * @param executedMoves the moves turned for the pair, in the solver's own frame
   */
  public static Algorithm matching(String pairCase, String executedMoves) {
    if (pairCase == null || executedMoves == null) {
      return null;
    }
    List<Algorithm> algorithms = forCase(pairCase);
    List<List<String>> forms = new ArrayList<>();
    for (Algorithm algorithm : algorithms) {
      forms.add(AlgorithmForm.comparable(algorithm.getMoves()));
    }
    int at = indexOfTurning(pairCase, forms, executedMoves);
    return at < 0 ? null : algorithms.get(at);
  }

  static int indexOfTurning(final String pairCase, List<List<String>> forms, String moves) {
    return AlgorithmForm.indexOfTurning(forms, moves, new AlgorithmForm.Drawn() {
      @Override
      public boolean solves(String stood) {
        return F2LCaseAlgorithms.solves(pairCase, stood);
      }
    });
  }

  /** Whether moves put the pair of the given case into front right, with the cross down. */
  static boolean solves(String pairCase, String moves) {
    try {
      return pairCase.equals(
          F2LCases.pairCase(Notation.caseState(moves), Cubies.D, Cubies.DFR, Cubies.FR));
    } catch (RuntimeException e) {
      return false; // unreadable, or a sequence that does not put the cube back down
    }
  }


  static String[][] rows() {
    return ALGORITHMS.clone();
  }

  public static final class Algorithm {

    private final String moves;
    private final String emptySlot;

    Algorithm(String moves, String emptySlot) {
      this.moves = moves;
      this.emptySlot = emptySlot;
    }

    public String getMoves() {
      return moves;
    }

    /** The slot ("fl", "br") that has to be empty for this algorithm, or null if none does. */
    public String getEmptySlot() {
      return emptySlot;
    }
  }
}
